apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hms

resources:
  - ../../base
  - httproute.yaml
  # configmap.yaml + sealed-secret.yaml are BOTH Jenkins-generated on every
  # production build. SealedSecret is sealed with prod-pub.pem so staging
  # encrypted data will NOT decrypt here.
  - configmap.yaml
  - sealed-secret.yaml

patches:
  - path: patch-image.yaml
    target:
      kind: Deployment
      name: hms-be
  - path: patch-resources.yaml
    target:
      kind: Deployment
      name: hms-be

commonLabels:
  env: production
