apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hms

resources:
  - ../../base
  - httproute.yaml
  # SealedSecret for PGPASSWORD. Sealed against prod cluster cert
  # (prod-pub.pem in Jenkins creds).
  - sealed-secret.yaml

patches:
  - path: patch-image.yaml
    target:
      kind: Deployment
      name: hms-pubsub
  - path: patch-resources.yaml
    target:
      kind: Deployment
      name: hms-pubsub
  - path: patch-configmap.yaml
    target:
      kind: ConfigMap
      name: hms-pubsub-config

commonLabels:
  env: production
