apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hms

resources:
  - ../../base
  - httproute.yaml

patches:
  - path: patch-image.yaml
    target:
      kind: Deployment
      name: hms-fe
  - path: patch-resources.yaml
    target:
      kind: Deployment
      name: hms-fe
  - path: patch-configmap.yaml
    target:
      kind: ConfigMap
      name: hms-fe-config

commonLabels:
  env: production
